# Bu, tüm fonksiyonlara uygulanacak ayarlar için doğru formattır.
[functions."*"]
  # Zaman aşımı süresini saniye cinsinden ayarla.
  # 25 saniye, karmaşık analiz işlemleri için yeterli olacaktır.
  timeout = 25
