# Netlify Functions (sunucusuz fonksiyonlar) için genel yapılandırma
[functions]
  # Tüm fonksiyonlar için zaman aşımı süresini saniye cinsinden ayarla
  # Pro planı için maksimum 26 saniyedir. 25 güvenli bir değerdir.
  # Ücretsiz planda bu süre daha düşük olabilir ancak denemeye değer.
  timeout = 25
